const copy = {
  ar: {
    loginTitle: 'تسجيل الدخول',
    loginSub: 'ادخل إلى لوحة التاجر أو الإدارة',
    registerTitle: 'إنشاء حساب تاجر',
    registerSub: 'سجّل متجرك وابدأ قبول المدفوعات خلال دقائق',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة السر؟',
    forgotTitle: 'استعادة كلمة السر',
    forgotSub: 'أدخل رقم الهاتف المرتبط بحسابك وسنرسل رمز تحقق عبر واتساب',
    resetTitle: 'تعيين كلمة سر جديدة',
    resetSub: 'أدخل الرمز المرسل إلى واتساب {phone} ثم كلمة السر الجديدة',
    sendWhatsappOtp: 'إرسال رمز واتساب',
    newPassword: 'كلمة السر الجديدة',
    confirmPassword: 'تأكيد كلمة السر',
    passwordHint: '٨ أحرف على الأقل، حرف ورقم',
    passwordMismatch: 'تأكيد كلمة السر غير مطابق',
    saveNewPassword: 'حفظ ودخول',
    changePhone: 'تغيير رقم الهاتف',
    rememberPassword: 'تذكرت كلمة السر؟',
    phoneRequired: 'يرجى إدخال رقم الهاتف',
    forgotFail: 'تعذّر إرسال رمز واتساب',
    resetFail: 'تعذّر تعيين كلمة السر',
    signIn: 'دخول',
    signingIn: 'جاري الدخول…',
    noAccount: 'ليس لديك حساب؟',
    registerLink: 'سجّل كتاجر',
    hasAccount: 'لديك حساب؟',
    loginLink: 'تسجيل الدخول',
    secureNote: 'اتصال آمن ومشفّر',
    fullName: 'الاسم الكامل',
    fullNameAr: 'الاسم الكامل بالعربية',
    fullNameEn: 'الاسم الكامل بالإنجليزية',
    businessName: 'اسم النشاط',
    businessNameAr: 'اسم النشاط بالعربية',
    phone: 'رقم الجوال',
    website: 'الموقع',
    createAccount: 'إنشاء الحساب',
    sendCode: 'إرسال رمز التحقق',
    otpTitle: 'تأكيد الرمز',
    otpSub: 'أدخل الرمز المرسل إلى {phone}',
    otpCode: 'رمز التحقق',
    verify: 'تأكيد وإنشاء الحساب',
    resend: 'إعادة الإرسال',
    noCode: 'لم يصلك الرمز؟',
    resendIn: 'إعادة الإرسال خلال {time}',
    back: 'العودة للنموذج',
    loginFail: 'تعذّر تسجيل الدخول',
    sessionExpired: 'انتهت جلستك. سجّل الدخول مجدداً للمتابعة.',
    registerFail: 'تعذّر التسجيل',
    otpFail: 'رمز غير صحيح أو منتهي',
    loading: 'جاري التحميل…',
    verifyLogin: 'تأكيد ودخول',
    loginWhatsappRequired: 'يتطلب تسجيل الدخول تأكيد رقم الواتساب',
    loginEmailRequired: 'يتطلب تسجيل الدخول تأكيد البريد',
    loginBothRequired: 'يتطلب تسجيل الدخول تأكيد الواتساب أو البريد',
    whatsappRequired: 'يتطلب التسجيل تأكيد رقم الواتساب',
    emailRequired: 'يتطلب التسجيل تأكيد البريد',
    bothRequired: 'يتطلب التسجيل تأكيد الواتساب أو البريد',
    sideLoginTitle: 'مرحباً بعودتك',
    sideLoginBody: 'إدارة المدفوعات والمحفظة والتقارير من لوحة واحدة.',
    sideRegisterTitle: 'ابدأ مع Fynexpay',
    sideRegisterBody: 'اربط متجرك بـ API موحّد وامنح زبائنك تجربة دفع سلسة.',
    pointSecure: 'حماية وتشفير للبيانات',
    pointWallet: 'محفظة وصافي فوري',
    pointFast: 'تفعيل سريع للتاجر',
    groupIdentity: 'بياناتك',
    groupBusiness: 'النشاط',
    groupAccess: 'بيانات الدخول',
    formStep: 'الخطوة 1 من 2',
    otpStep: 'الخطوة 2 من 2',
    sideForgotTitle: 'استعادة آمنة',
    sideForgotBody: 'نرسل رمز التحقق إلى واتساب المسجّل ثم تعيّن كلمة سر جديدة.',
    backHome: 'العودة للرئيسية'
  },
  en: {
    loginTitle: 'Sign in',
    loginSub: 'Access the merchant or admin dashboard',
    registerTitle: 'Create merchant account',
    registerSub: 'Register your store and start accepting payments in minutes',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    forgotTitle: 'Reset password',
    forgotSub: 'Enter the phone number on your account and we will send a WhatsApp code',
    resetTitle: 'Set a new password',
    resetSub: 'Enter the WhatsApp code sent to {phone}, then choose a new password',
    sendWhatsappOtp: 'Send WhatsApp code',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    passwordHint: 'At least 8 characters, with a letter and a number',
    passwordMismatch: 'Password confirmation does not match',
    saveNewPassword: 'Save and sign in',
    changePhone: 'Change phone number',
    rememberPassword: 'Remembered your password?',
    phoneRequired: 'Please enter a phone number',
    forgotFail: 'Could not send the WhatsApp code',
    resetFail: 'Could not reset the password',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    noAccount: "Don't have an account?",
    registerLink: 'Register as merchant',
    hasAccount: 'Already have an account?',
    loginLink: 'Sign in',
    secureNote: 'Secure encrypted connection',
    fullName: 'Full name',
    fullNameAr: 'Full name (Arabic)',
    fullNameEn: 'Full name (English)',
    businessName: 'Business name',
    businessNameAr: 'Business name (Arabic)',
    phone: 'Mobile number',
    website: 'Website',
    createAccount: 'Create account',
    sendCode: 'Send verification code',
    otpTitle: 'Verify code',
    otpSub: 'Enter the code sent to {phone}',
    otpCode: 'Verification code',
    verify: 'Verify & create account',
    resend: 'Resend',
    noCode: "Didn't get the code?",
    resendIn: 'Resend in {time}',
    back: 'Back to form',
    loginFail: 'Could not sign in',
    sessionExpired: 'Your session expired. Sign in again to continue.',
    registerFail: 'Could not register',
    otpFail: 'Invalid or expired code',
    loading: 'Loading…',
    verifyLogin: 'Verify & sign in',
    loginWhatsappRequired: 'Sign-in requires WhatsApp verification',
    loginEmailRequired: 'Sign-in requires email verification',
    loginBothRequired: 'Sign-in requires WhatsApp or email verification',
    whatsappRequired: 'Registration requires WhatsApp verification',
    emailRequired: 'Registration requires email verification',
    bothRequired: 'Registration requires WhatsApp or email verification',
    sideLoginTitle: 'Welcome back',
    sideLoginBody: 'Manage payments, wallet, and reports from one dashboard.',
    sideRegisterTitle: 'Start with Fynexpay',
    sideRegisterBody: 'Connect your store with one API and give customers a smooth checkout.',
    pointSecure: 'Data protection & encryption',
    pointWallet: 'Wallet with instant net credit',
    pointFast: 'Fast merchant activation',
    groupIdentity: 'Your details',
    groupBusiness: 'Business',
    groupAccess: 'Sign-in details',
    formStep: 'Step 1 of 2',
    otpStep: 'Step 2 of 2',
    sideForgotTitle: 'Secure recovery',
    sideForgotBody: 'We send a code to the registered WhatsApp number, then you set a new password.',
    backHome: 'Back to home'
  }
}

export function useAuthCopy(localeRef) {
  return {
    t: (key, params = {}) => {
      const pack = copy[localeRef.value === 'en' ? 'en' : 'ar'] || copy.ar
      let text = pack[key] || key
      for (const [k, v] of Object.entries(params)) {
        text = text.replace(`{${k}}`, v)
      }
      return text
    }
  }
}

export function handoffToDashboard(dashboardUrl, data) {
  const user = {
    userId: data.userId,
    email: data.email,
    fullName: data.fullName,
    role: data.role,
    merchantId: data.merchantId,
    merchantStatus: data.merchantStatus
  }
  const payload = btoa(unescape(encodeURIComponent(JSON.stringify({
    token: data.token,
    user
  }))))
  const base = String(dashboardUrl || 'http://localhost:5173').replace(/\/$/, '')
  window.location.href = `${base}/auth/handoff#${payload}`
}
